# Default Configuration

spring:
  profiles:
    active: dev

  main:
    banner-mode: "off"

server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

---
# Configuration for Development Environment

spring:
  profiles:
    - dev
    - development

server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"

---
# Configuration for Staging Environment

spring:
  profiles:
    - staging

---
# Configuration for Production Environment

spring:
  profiles:
    - prod
    - production
